/* ==========================================================================
   EFL GLOBAL — Shared travel-form PDF generator
   Used by BOTH the Executive Portal (script.js) and the Admin Dashboard
   (admin.js) — one engine, so the forms always match wherever they're
   generated from. Requires jsPDF + jspdf-autotable to be loaded first.
   ========================================================================== */

const FORM_GRAY = [61, 63, 66];
const FORM_ORANGE = [255, 106, 19];
const FORM_INK = [20, 20, 20];
const FORM_MUTED = [120, 120, 120];

let LOGO_DATA_URL = null;
async function getLogoDataUrl() {
  if (LOGO_DATA_URL) return LOGO_DATA_URL;
  try {
    const res = await fetch('assets/brand/efl-mark-256.png');
    const blob = await res.blob();
    LOGO_DATA_URL = await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (err) {
    LOGO_DATA_URL = null;
  }
  return LOGO_DATA_URL;
}

// Trip's real date span, derived only from structured flight dateISO values
// (never parsed from free-text like "17 - 20th July") so it's reliable or absent.
function getTripDateSpanISO(trip) {
  const isos = (trip.flights || []).map(f => f.dateISO).filter(Boolean).sort();
  if (!isos.length) return null;
  const d1 = new Date(isos[0] + 'T00:00:00');
  const d2 = new Date(isos[isos.length - 1] + 'T00:00:00');
  const days = Math.round((d2 - d1) / 86400000) + 1;
  return { startISO: isos[0], endISO: isos[isos.length - 1], days };
}

async function newFormDoc(title, subtitle) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(...FORM_GRAY);
  doc.rect(0, 0, pageWidth, 70, 'F');

  const logo = await getLogoDataUrl();
  if (logo) {
    try { doc.addImage(logo, 'PNG', pageWidth - 66, 14, 42, 42); } catch (err) { /* logo optional */ }
  }

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text('EFL GLOBAL', 36, 30);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('EXECUTIVE TRAVEL PORTAL', 36, 46);

  doc.setTextColor(...FORM_ORANGE);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(title, 36, 100);

  let y = 100;
  if (subtitle) {
    doc.setTextColor(...FORM_GRAY);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);
    doc.text(subtitle, 36, 118);
    y = 118;
  }

  return { doc, startY: y + 24, pageWidth };
}

function addFormFooter(doc, note) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.setFont('helvetica', 'italic');
  doc.text(
    note || 'Generated by the EFL Global Executive Travel Portal from saved trip records. Verify all details before submission.',
    36, pageHeight - 28, { maxWidth: pageWidth - 72 }
  );
}

// Draws label/value pairs two-per-row, returns the y position after the grid.
function drawFieldGrid(doc, x, y, pairs, colWidth) {
  let cx = x, cy = y, col = 0;
  pairs.forEach(([label, value]) => {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...FORM_MUTED);
    doc.text(String(label).toUpperCase(), cx, cy);
    doc.setFont('helvetica', 'bold'); doc.setFontSize(10.5); doc.setTextColor(...FORM_INK);
    doc.text(String(value || '\u2014'), cx, cy + 14);
    col++;
    if (col % 2 === 0) { cx = x; cy += 34; } else { cx = x + colWidth; }
  });
  return col % 2 === 0 ? cy : cy + 34;
}

async function generateTRF(trip) {
  const { doc, startY, pageWidth } = await newFormDoc('Travel Request Form (TRF)', 'Pre-Travel Approval Request');
  const marginX = 36;
  const half = (pageWidth - marginX * 2) / 2;
  let y = startY;

  y = drawFieldGrid(doc, marginX, y, [
    ['Name', trip.traveller.name], ['Designation', trip.traveller.position],
    ['Entity', trip.meta.companyName], ['Trip ID', trip.traveller.tripId],
    ['Destination', trip.traveller.destination], ['Travel Dates', trip.traveller.dates],
  ], half);
  y += 6;

  doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(...FORM_GRAY);
  doc.text('Business Purpose', marginX, y);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(...FORM_INK);
  doc.text(trip.meta.tripName || '\u2014', marginX, y + 14, { maxWidth: pageWidth - marginX * 2 });
  y += 34;

  if (trip.meetings && trip.meetings.length) {
    doc.autoTable({
      startY: y, margin: { left: marginX, right: marginX },
      head: [['Party to be Visited', 'Location', 'Date']],
      body: trip.meetings.map(m => [m.with || '\u2014', m.location || '\u2014', m.date || '\u2014']),
      headStyles: { fillColor: FORM_GRAY, textColor: 255, fontSize: 9 },
      bodyStyles: { fontSize: 9 }, theme: 'grid'
    });
    y = doc.lastAutoTable.finalY + 20;
  }

  doc.autoTable({
    startY: y, margin: { left: marginX, right: marginX },
    head: [['Routing', 'Carrier', 'Class', 'Date', 'PNR']],
    body: (trip.flights || []).length
      ? trip.flights.map(f => [f.route || '\u2014', f.airline || '\u2014', f.class || '\u2014', f.date || '\u2014', f.pnr || '\u2014'])
      : [['\u2014', '\u2014', '\u2014', 'No flights on file', '\u2014']],
    headStyles: { fillColor: FORM_ORANGE, textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 }, theme: 'grid'
  });
  y = doc.lastAutoTable.finalY + 36;

  doc.setFontSize(9); doc.setTextColor(80, 80, 80); doc.setFont('helvetica', 'normal');
  doc.text('Requested By / Date: ________________________________', marginX, y);
  doc.text('Approved By / Date: ________________________________', marginX + half + 6, y);

  addFormFooter(doc);
  doc.save(`TRF-${trip.traveller.tripId}.pdf`);
}

// policyData: the parsed contents of data/travel-policy.json (optional — the
// form still generates without it, just without the auto-computed total).
async function generateMealPerDiem(trip, policyData) {
  const { doc, startY, pageWidth } = await newFormDoc('Meal Per Diem Claim Form', 'Pre-Travel Estimate');
  const marginX = 36;
  const half = (pageWidth - marginX * 2) / 2;
  let y = startY;

  y = drawFieldGrid(doc, marginX, y, [
    ['Name', trip.traveller.name], ['Designation', trip.traveller.position],
    ['Entity', trip.meta.companyName], ['Travel Zone', trip.traveller.zone || 'Not set'],
  ], half);
  y += 6;

  doc.autoTable({
    startY: y, margin: { left: marginX, right: marginX },
    head: [['Flight', 'Date', 'Departs', 'Arrives', 'Route']],
    body: (trip.flights || []).length
      ? trip.flights.map(f => [`${f.airline || ''} ${f.flightNumber || ''}`.trim() || '\u2014', f.date || '\u2014', f.departure || '\u2014', f.arrival || '\u2014', f.route || '\u2014'])
      : [['\u2014', '\u2014', '\u2014', '\u2014', 'No flights on file']],
    headStyles: { fillColor: FORM_GRAY, textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 }, theme: 'grid'
  });
  y = doc.lastAutoTable.finalY + 20;

  const policyRow = (policyData && trip.traveller.zone) ? policyData.perDiemByZone.rows.find(r => r.zone === trip.traveller.zone) : null;
  const rate = policyRow ? Number((policyRow.dailyLimit.match(/[\d.]+/) || [])[0]) : null;
  const currency = policyRow ? policyRow.dailyLimit.split(' ')[0] : (trip.expenses?.currency || 'USD');
  const span = getTripDateSpanISO(trip);
  const days = span ? span.days : null;
  const total = (rate != null && days != null) ? rate * days : null;

  doc.autoTable({
    startY: y, margin: { left: marginX, right: marginX },
    head: [['Destination', 'Zone', 'Per Diem Rate', 'No. of Days', 'Total']],
    body: [[
      trip.traveller.destination || '\u2014',
      trip.traveller.zone || 'Not set',
      policyRow ? policyRow.dailyLimit : '\u2014',
      days != null ? String(days) : '\u2014 (no flight dates on file)',
      total != null ? `${currency} ${total.toFixed(2)}` : '\u2014'
    ]],
    headStyles: { fillColor: FORM_ORANGE, textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9.5, fontStyle: 'bold' }, theme: 'grid'
  });
  y = doc.lastAutoTable.finalY + 40;

  doc.setFontSize(9); doc.setTextColor(80, 80, 80); doc.setFont('helvetica', 'normal');
  doc.text('Employee Signature / Date: ________________________________', marginX, y); y += 22;
  doc.text('Approver Signature / Date: ________________________________', marginX, y);

  addFormFooter(doc, 'Per diem calculated from the travel policy and the flight dates on file. Confirm actual travel dates before submission.');
  doc.save(`Meal-Per-Diem-${trip.traveller.tripId}.pdf`);
}

async function generateExpenseClaim(trip) {
  const { doc, startY, pageWidth } = await newFormDoc('Travel Expense Claim Form', 'Post-Travel Reimbursement');
  const marginX = 36;
  const half = (pageWidth - marginX * 2) / 2;
  let y = startY;

  y = drawFieldGrid(doc, marginX, y, [
    ['Name', trip.traveller.name], ['Designation', trip.traveller.position],
    ['Entity', trip.meta.companyName], ['Trip Dates', trip.traveller.dates],
  ], half);
  y += 6;

  const items = (trip.expenses && trip.expenses.items) || [];
  const currency = (trip.expenses && trip.expenses.currency) || 'USD';
  doc.autoTable({
    startY: y, margin: { left: marginX, right: marginX },
    head: [['#', 'Date', 'Category', 'Purpose', 'Amount']],
    body: items.length
      ? items.map((it, i) => [String(i + 1), it.date || '\u2014', it.category || '\u2014', it.description || '\u2014', `${currency} ${Number(it.amount || 0).toFixed(2)}`])
      : [['\u2014', '\u2014', '\u2014', 'No expenses logged for this trip yet', '\u2014']],
    headStyles: { fillColor: FORM_GRAY, textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 }, theme: 'grid'
  });
  y = doc.lastAutoTable.finalY + 18;

  const total = items.reduce((sum, it) => sum + Number(it.amount || 0), 0);
  doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(...FORM_GRAY);
  doc.text(`Claimed Amount: ${currency} ${total.toFixed(2)}`, marginX, y);
  y += 36;

  doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(80, 80, 80);
  doc.text('Employee Signature / Date: ________________________________', marginX, y);

  addFormFooter(doc, 'Expense lines pulled from logged trip expenses. Attach original receipts before submission.');
  doc.save(`Expense-Claim-${trip.traveller.tripId}.pdf`);
}

async function generatePostTravelReport(trip) {
  const { doc, startY, pageWidth } = await newFormDoc('Post Travel Expense Report', 'Post-Travel Summary');
  const marginX = 36;
  const half = (pageWidth - marginX * 2) / 2;
  let y = startY;

  y = drawFieldGrid(doc, marginX, y, [
    ['Name', trip.traveller.name], ['Designation', trip.traveller.position],
    ['Entity', trip.meta.companyName], ['Travel Duration', trip.traveller.dates],
  ], half);
  y += 8;

  doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(...FORM_ORANGE);
  doc.text('Travel, Transportation & Accommodation', marginX, y);

  const travelRows = [];
  (trip.flights || []).forEach(f => travelRows.push([f.date || '\u2014', f.route || '\u2014', 'Flight', f.class || '\u2014', '']));
  (trip.hotels || []).forEach(h => travelRows.push([h.checkIn || '\u2014', h.name || '\u2014', 'Hotel', h.room || '\u2014', '']));
  doc.autoTable({
    startY: y + 8, margin: { left: marginX, right: marginX },
    head: [['Date', 'City / Hotel', 'Type', 'Class / Room', 'Amount (fill in)']],
    body: travelRows.length ? travelRows : [['\u2014', 'No flights or hotels on file', '\u2014', '\u2014', '\u2014']],
    headStyles: { fillColor: FORM_GRAY, textColor: 255, fontSize: 8.5 },
    bodyStyles: { fontSize: 8.5 }, theme: 'grid'
  });
  y = doc.lastAutoTable.finalY + 22;

  if (trip.meetings && trip.meetings.length) {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(...FORM_ORANGE);
    doc.text('Entertainment / Meetings', marginX, y);
    doc.autoTable({
      startY: y + 8, margin: { left: marginX, right: marginX },
      head: [['Guest', 'Place', 'Purpose', 'Amount (fill in)']],
      body: trip.meetings.map(m => [m.with || '\u2014', m.location || '\u2014', m.title || '\u2014', '']),
      headStyles: { fillColor: FORM_GRAY, textColor: 255, fontSize: 8.5 },
      bodyStyles: { fontSize: 8.5 }, theme: 'grid'
    });
    y = doc.lastAutoTable.finalY + 22;
  }

  const items = (trip.expenses && trip.expenses.items) || [];
  const currency = (trip.expenses && trip.expenses.currency) || 'USD';
  doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(...FORM_ORANGE);
  doc.text('Other Expenses', marginX, y);
  doc.autoTable({
    startY: y + 8, margin: { left: marginX, right: marginX },
    head: [['Date', 'Type', 'Purpose', 'Amount']],
    body: items.length
      ? items.map(it => [it.date || '\u2014', it.category || '\u2014', it.description || '\u2014', `${currency} ${Number(it.amount || 0).toFixed(2)}`])
      : [['\u2014', '\u2014', 'No other expenses logged', '\u2014']],
    headStyles: { fillColor: FORM_GRAY, textColor: 255, fontSize: 8.5 },
    bodyStyles: { fontSize: 8.5 }, theme: 'grid'
  });
  y = doc.lastAutoTable.finalY + 18;

  const otherTotal = items.reduce((sum, it) => sum + Number(it.amount || 0), 0);
  doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(...FORM_GRAY);
  doc.text(`Other Expenses Subtotal: ${currency} ${otherTotal.toFixed(2)}`, marginX, y);

  addFormFooter(doc, 'Dates, routes, and logged expenses are pre-filled from trip records. Transportation, accommodation, and entertainment amounts need manual entry from receipts.');
  doc.save(`Post-Travel-Report-${trip.traveller.tripId}.pdf`);
}

// Shared dispatcher — used by both the portal and admin dashboard.
// trip: the full trip object. policyData: parsed travel-policy.json (or null).
async function generateFormByKind(kind, trip, policyData) {
  if (kind === 'trf') return generateTRF(trip);
  if (kind === 'perdiem') return generateMealPerDiem(trip, policyData);
  if (kind === 'claim') return generateExpenseClaim(trip);
  if (kind === 'posttravel') return generatePostTravelReport(trip);
  throw new Error('Unknown form type: ' + kind);
}
